services:
  camaredn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camaredn_app
    shm_size: '256m'
    volumes:
      # Mount the local config.yaml to the container's /app/config.yaml
      - ./config.yaml:/app/config.yaml
      # Mount the local directory /srv/camaredn/data to /app/data in the container
      - /srv/camaredn/data:/app/data
    command: /app/config.yaml
  nginx:
    image: nginx:alpine
    container_name: camaredn_webserver
    ports:
      - "5802:80"  # Expose port 8080 on the host to port 80 in the container
    volumes:
      # Mount the same data directory to the Nginx container to serve it
      - /srv/camaredn/data:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - camaredn
