services:
  camaredn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camaredn_app
    shm_size: '256m'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card1
    group_add:
      - video # For Intel OpenCL
      - 993 # render
        #      - render # For Intel OpenCL
    volumes:
      # Mount the local config.yaml to the container's /app/config.yaml
      - ./config.yaml:/app/config.yaml
      # Mount the local directory /srv/camaredn/data to /app/data in the container
      - /srv/camaredn/data:/app/data
      # OpenCL
      - /etc/OpenCL/vendors:/etc/OpenCL/vendors
    command: /app/config.yaml
  nginx:
    image: nginx:alpine
    container_name: camaredn_webserver
    ports:
      - "5802:80"  # Expose port 8080 on the host to port 80 in the container
      - "5803:443" # Expose port 5803 on the host to port 443 for HTTPS in the container
    volumes:
      # Mount the same data directory to the Nginx container to serve it
      - /srv/camaredn/data:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount SSL certificates into the Nginx container
      - ./ssl/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./ssl/key.pem:/etc/nginx/ssl/key.pem:ro
    depends_on:
      - camaredn
